// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newArticlesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "articles",
		Short:  "Picnic product catalogue: search, suggest, and inspect articles",
		Hidden: true,
	}

	cmd.AddCommand(newArticlesCategoryCmd(flags))
	cmd.AddCommand(newArticlesFindCmd(flags))
	cmd.AddCommand(newArticlesGetCmd(flags))
	cmd.AddCommand(newArticlesSuggestCmd(flags))
	return cmd
}
