// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCartCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "cart",
		Short:  "Active shopping cart for the authenticated user",
		Hidden: true,
	}

	cmd.AddCommand(newCartAddCmd(flags))
	cmd.AddCommand(newCartCheckoutCmd(flags))
	cmd.AddCommand(newCartClearCmd(flags))
	cmd.AddCommand(newCartGetCmd(flags))
	cmd.AddCommand(newCartRemoveCmd(flags))
	cmd.AddCommand(newCartSetSlotCmd(flags))
	return cmd
}
