// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDeliveriesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "deliveries",
		Short:  "Past and active deliveries",
		Hidden: true,
	}

	cmd.AddCommand(newDeliveriesCancelCmd(flags))
	cmd.AddCommand(newDeliveriesGetCmd(flags))
	cmd.AddCommand(newDeliveriesListCmd(flags))
	cmd.AddCommand(newDeliveriesPositionCmd(flags))
	cmd.AddCommand(newDeliveriesRateCmd(flags))
	cmd.AddCommand(newDeliveriesResendInvoiceCmd(flags))
	cmd.AddCommand(newDeliveriesScenarioCmd(flags))
	return cmd
}
