// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newListsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "lists",
		Short:  "Shopping lists (saved product collections)",
		Hidden: true,
	}

	cmd.AddCommand(newListsGetCmd(flags))
	cmd.AddCommand(newListsListCmd(flags))
	return cmd
}
