// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPaymentCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "payment",
		Short:  "Payment profile and wallet",
		Hidden: true,
	}

	cmd.AddCommand(newPaymentProfileCmd(flags))
	cmd.AddCommand(newPaymentWalletCmd(flags))
	cmd.AddCommand(newPaymentWalletDetailCmd(flags))
	return cmd
}
