// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUserCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "user",
		Short:  "Authenticated Picnic user profile and account details",
		Hidden: true,
	}

	cmd.AddCommand(newUserGetCmd(flags))
	cmd.AddCommand(newUserInfoCmd(flags))
	return cmd
}
